database:
  host: localhost
  port: 5432
  database: airflow
  user: postgres
  password: ${DB_PASSWORD}

app:
  template_directory: templates
  output_directory: generated_dags
  log_level: INFO
  base_directory: ${APP_BASE_DIR}