version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_DATABASE=bitnami_airflow
      - POSTGRESQL_USERNAME=bn_airflow
      - POSTGRESQL_PASSWORD=bitnami1
    volumes:
      - postgresql_data:/bitnami/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bn_airflow"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - redis_data:/bitnami
    ports:
      - "6379:6379"  # Expose Redis port

  airflow-scheduler:
    image: bitnami/airflow:latest
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=True
      - AIRFLOW_COMPONENT=scheduler  # Changed from AIRFLOW_COMPONENT_TYPE
      - AIRFLOW_DATABASE_HOST=postgresql
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_REDIS_HOST=redis
      - AIRFLOW_EXECUTOR=CeleryExecutor
      # Additional configurations
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://bn_airflow:bitnami1@postgresql/bitnami_airflow
      - AIRFLOW__CELERY__WORKER_CONCURRENCY=2

  airflow-worker:
    image: bitnami/airflow:latest
    depends_on:
      - postgresql
      - redis
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
    environment:
      - AIRFLOW_COMPONENT=worker  # Changed from AIRFLOW_COMPONENT_TYPE
      - AIRFLOW_DATABASE_HOST=postgresql
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_REDIS_HOST=redis
      - AIRFLOW_EXECUTOR=CeleryExecutor
      # Additional configurations
      - AIRFLOW__CELERY__BROKER_URL=redis://redis:6379/0
      - AIRFLOW__CELERY__RESULT_BACKEND=db+postgresql://bn_airflow:bitnami1@postgresql/bitnami_airflow
      - AIRFLOW__CELERY__WORKER_CONCURRENCY=2

  airflow:
    image: bitnami/airflow:latest
    depends_on:
      - postgresql
      - redis
      - airflow-scheduler
      - airflow-worker
    volumes:
      - ./dags:/opt/bitnami/airflow/dags
    ports:
      - '8080:8080'
    environment:
      - AIRFLOW_DATABASE_HOST=postgresql
      - AIRFLOW_DATABASE_NAME=bitnami_airflow
      - AIRFLOW_DATABASE_USERNAME=bn_airflow
      - AIRFLOW_DATABASE_PASSWORD=bitnami1
      - AIRFLOW_REDIS_HOST=redis
      - AIRFLOW_EXECUTOR=CeleryExecutor
      - AIRFLOW_USERNAME=user
      - AIRFLOW_PASSWORD=bitnami123
      - AIRFLOW_EMAIL=user@example.com
      # Additional configurations
      - AIRFLOW__WEBSERVER__UPDATE_FAB_PERMS=True
      - AIRFLOW__WEBSERVER__WORKERS=2
      - AIRFLOW__WEBSERVER__WORKER_TIMEOUT=300
      - GUNICORN_CMD_ARGS="--timeout 300 --workers 2"

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local